jbcoe/value_types

BUILD.bazel, CMakeLists.txt, indirect_gtest.cc, indirect_with_allocators.h, polymorphic_gtest.cc, polymorphic_with_allocators.h
Constructors taking an allocator should be added in a later PR.
More allocator-focussed tests should be added to ensure that we're cleaning things up correctly (again a later PR).
=> Add minimal implementations of indirect and polymorphic with basic allocator support

DRAFT.md, indirect.h, indirect_test.cc
This is a significant design change as it prevents `indirect` from holding a object of a derived type of a non-copyable base class (if the base class were also non-movable then using `indirect` would be fine). Given the check on movability, we can still support moving `indirect<T>` when `T` is a non-movable type (like a mutex).
This change avoid allocation and makes `indirect` cheaper, which as a low-cost abstraction is the direction we want.
=> Make indirect-assign conditionally not allocate

DRAFT.md
Based wording on that of optional: https://eel.is/c++draft/optional
Fixes #46
=> Add wording for hash of indirect

DRAFT.md, indirect.h, indirect_test.cc
Initial draft, will push up tests and add to the spec shortly.
=> Extend indirect to work with std::format

.github/workflows/cmake.yml, BUILD.bazel, DRAFT.md, indirect.h, indirect_pimpl.cc, indirect_pimpl.h, indirect_pimpl_use.cc, polymorphic.h, polymorphic_pimpl.cc, polymorphic_pimpl.h, polymorphic_pimpl_use.cc
Add tests for compiling with incomplete types.
Update Draft and headers: some requires clauses need to be static_asserts to support incomplete types.
See: https://timsong-cpp.github.io/cppwp/n4861/structure for the difference between _Constraints_ and _Mandates_.
Thanks to Bengt Gustaffson for pointing out the need for these changes.
=> Fixes for incomplete type support

experimental/polymorphic_sbo.h, polymorphic_test.cc
* Improve helper functions for SBO.
* update_ptr is removed as it did unnecessary type index lookup.
* Add untested optimisation for trivially copyable types
=> Use allocator for create/destroy in SBO

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
Devcontainer means users can press '.' on our github page and start up VS Code in-browser.
Opening a terminal will fire up a Docker-backed container instance with developer tools installed to build code and run tests with CMake and Bazel.
=> Definine a devcontainer with docker

DRAFT.md, experimental/polymorphic_sbo.h, polymorphic_test.cc
control_block was unintentionally made allocator_aware.
Thanks to Nina Ranns and Josh Berne
Fixes #112
=> Fix for compile error in SBO impl

DRAFT.md, README.md, benchmarks/indirect_benchmark.cc, compile_checks/indirect_consteval.cc, indirect.h, indirect_test.cc
The constructor argument is just noise. Consistency with polymorphic is artificial.
@BengtGustafsson pointed this out some time ago and I've not done anything about it.
=> Remove std::in_place argument to indirect constructor

.github/workflows/clang-format-check.yml, .pre-commit-config.yaml, benchmarks/polymorphic_benchmark.cc, compile_checks/indirect_consteval.cc, compile_checks/polymorphic_pimpl_use.cc, docs/developer-guide.md, indirect_test.cc
Use clang-format 17 to check format for source code.
=> Add clang-format check to github actions

DRAFT.md
@sean-parent LEWG wanted discussion of optional specialization removing with the explicit understanding that it can be added (and probably should be added) as another paper for C++26. Time was against us and this was impeding consensus. It's simple enough to look at in isolation.
=> Remove optional specialization as requested by LEWG

indirect.h, polymorphic.h
Right now, including both indirect.h and polymorphic.h will lead to a compiler error: `error: redefinition of 'unreachable'`. Because both headers define the function `unreachable`. By wrapping it in a macro, we ensure that it will only be defined once.
=> Define `unreachable` only once, even if including both headers

DRAFT.md
Reviewed up to indirect.ctor.
- Some changes of free-store-allocated to dynamically-allocated in abstract/design sections.
I think that these types permit small-object optimisations, in which case they may not be on the free-store?
Also, an allocator could allocate them in stack storage, so may not necessarily be on the “free store”.
- Simplified paragraph in abstract relating to const-propagation.
This type is not necessarily only used as a member of a parent object.
Just talk about constness of `polymorphic<T>` propagating the constness to the `T` rather than talking about constness of the parent object influencing that.
- Remove sentence about allocator requiring that move construction is non-throwing.
I think this is already guaranteed by the requirements of Cpp17Allocator and so may …
=> Minor fixes/suggestions

DRAFT.md
Requirements on the user should use the word 'shall' rather than 'must'.
=> Use 'shall' for requirements placed on the user

DRAFT.md
Use the `Allocator` template parameter instead of the undefined `A` name.
=> Fix signatures of `indirect` comparison operators

DRAFT.md
The Constraints section of the wording was trying to say that two types were comparable, rather than two const-ref lvalues to objects of those types being comparable.
=> Tweak wording for `indirect` comparison operators

DRAFT.md
Add this requirement to the front-matter of `indirect` and `polymorphic` and remove it from the preconditions of each of the various member functions that might allocate.
=> Move requirement for Allocator to meet Cpp17Allocator requirements to front matter

DRAFT.md
For the copy/alloc+copy/alloc+move constructors specify the effects in terms of other constructors as a way of simplifying the specification.
NOTE: That this PR also makes the `indirect(std::allocator_arg_t, const Allocator& alloc, indirect&& other)` now conditionally `noexcept`. This is required because the case where `alloc != other.get_allocator()` may require allocating a new object and move-constructing the new object from `*other`.
The main question here is whether the post-condition that `other` is valueless is required to hold.
If it allocates a new object rather than taking ownership of `other`'s object, do we want to force `other` to become valueless, or just leave it having a value that is in a moved-from state?
=> Simplify some constructors by delegating to other constructors

DRAFT.md
- add code-font to `true` and `false`
- Change `allocator` -> `allocator_` where it is referring to the exposition-only member.
- Parenthesize `(*this).get_allocator()`
=> Add code-font where necessary and other minor typos in wording

DRAFT.md
This should now provide the strong-exception guarantee in case that the allocation or copy-construction fails (partially addressing #230). Now defines effects in terms of move-assignment of a newly constructed object.
Updated to make it constrain on copy-constructibility of T instead of mandating (partially addressing #199).
Updated to handle self-assignment by stating this has no effects (addressing #232).
Add missing _Returns_ clause.
NOTE: The move-assignment operator wording still needs massaging in a similar way, however.
=> Revise wording of `indirect` copy-assignment operator

CMakeLists.txt, cmake/vt_add_test.cmake, compatibility/polymorphic_cxx14.h, experimental/polymorphic_inline_vtable.h, experimental/polymorphic_sbo.h, polymorphic.h, polymorphic_test.cc
Allow CMake tests to be made manual-only (SBO tests fail).
=> Remove SBO-specific detail from polymorphic

DRAFT.md
I made an editing pass on the wording.  There's likely aspects that I did wrong, so pick and choose what you keep accordingly.
Most of the things I saw where LWG and editorial level, but you might as well fix those while you are in the period between meetings.
The biggest design'ish thing I saw that needs to be resolved is constraints vs. mandates.  I've got a note about that below.  The biggest wording thing I saw that I didn't attempt to fix was the possible technique of declaring these facilities as allocator-aware containers.  That has the potential to remove lots of words.
Below are my stream of consciousness review notes.
--------------------------------------------
typesetting with .md may be a challenge.  Maybe the typesetting requirements for this wording aren't that bad though. …
=> Ben Craig's quick review of wording

.bazelrc, DRAFT.md, cmake/vt_add_test.cmake, indirect.h, indirect_test.cc, polymorphic.h, polymorphic_test.cc
Tests to make sure that self-swap and self-assign should do not make an object valueless.
=> Ensure that swap with self is safe

DRAFT.md
Template trick:
```
template typename <U=T>
indirect& operator=(const indirect&);
```
led to:
object of type 'xyz::indirect<S, TaggingAllocator<S>>' cannot be assigned because its copy assignment
operator is implicitly deleted
=> Convert constraint to mandate for indirect assign

feature_check.h, indirect_test.cc
This PR fixed numerous warning in the output when compiling under Visual Studio
=> Use <memory_resource> only for C++17 and ensure std::exception base is public

cmake/xyz_add_test.cmake
So it turn out that Visual Studio has been incorrectly defining the `__cplusplus` macro all along, and so checks which depend on this, just as memory resource tests, are incorrectly not executed on Windows.
This is described at the following:
- https://stackoverflow.com/a/56483887/4764531
- https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/
The compiler option `/Zc:__cplusplus` ensures Visual Studio update the value of this macro.
=> Ensure Visual Studio correctly declares the __cplusplus macro

DRAFT.md
There is no reason for violating this rule to result in UB, just make it ill-formed. The standard allocator-aware containers make it ill-formed since C++20, you should follow suit.
=> Using an allocator with wrong value_type should not be undefined

DRAFT.md
There is no reason to mention internal types here. That's needed for node-based containers like `std::set<T>` and `std::map<T>` where we allocate nodes of internal types, and construct a `T`. For those containers we need two different allocator types, so the container stores one allocator type and rebinds to get the other allocator type. That's not relevant for your types, you have no internal node types. You allocate a `T` and construct a `T`, so the `indirect<T>` can just store an `Allocator` and use that directly to both allocate/deallocate and construct/destroy.
=> No need to rebind allocators

DRAFT.md, indirect.h, indirect_cxx14.h, indirect_test.cc, polymorphic.h, polymorphic_cxx14.h, polymorphic_test.cc, presentations/vocabulary_types_2023_11_8.md
Copy, move and swap of a valueless object should be permitted to be consistent with variant's handling of its own valueless state.
=> Allow copy, move and assign from the valueless state

.gitignore, MODULE.bazel
This is a short-term workaround until we upgrade our bazel setup to use MODULES.
=> Commit empty MODULE.bazel file and ignore lockfile

DRAFT.md, indirect.h, indirect_cxx14.h
Use concept checks on deduced types to delay constraint checks and allow incomplete T for class instantiation.
`indirect<T>` no longer supports `T` where `T` is not copy-constructible.
Fixes #313
=> Ensure that T in indirect<T> is copy_constructible using constraints

DRAFT.md
We can't make type requirements on possibly incomplete types.
Fixes #334
=> Remove unnecessary Mandates

polymorphic_cxx14.h, polymorphic_test.cc
The non-C++14 `polymorphic` requires C++20.
If the C++14 `polymorphic` is being used in C++17 mode, then both `xyz::in_place_type_t` and `std::in_place_type_t` will exist. Make sure they have the same definition in all places. This fixes a compilation error when compiling "polymorphic_test.h" with `-std=c++17 -DXYZ_POLYMORPHIC_CXX_14`.
Also, match the open/close of `namespace xyz` with the open/close of preprocessor conditionals, so that you don't get a compilation error when compiling "indirect.h" followed by "polymorphic_cxx14.h" in `-std=c++20` mode.
=> Fix issues using "polymorphic_cxx14.h" in C++17 and later

DRAFT.md, DRAFT_COROLLARY.md
The standard uses `class` in template heads, not `typename`. And `std::` should not be present on `std::allocator_arg_t` or `std::allocator_traits`.
=> Minor fixes

DRAFT.md
Reference wrapper does not mandate complete types as it's legal to define 
```
class S;
bool operator==(const S& lhs, const S& rhs);
```
making `s1==s2` well-formed where `s1` and `s2` are instances of `const S&` even though `S` is incomplete.
=> Remove spurious complete type checks

DEVELOPMENT.md, DRAFT.md, DRAFT_COROLLARY.md
We already mention allocators in:  Class template polymorphic general [polymorphic.general] 
_In every specialization `polymorphic<T, Allocator>`, if the type
`allocator_traits<Allocator>::value_type` is not the same type as`T`, the
program is ill-formed. Every object of type `polymorphic<T, Allocator>` uses an
object of type `Allocator` to allocate and free storage for the owned object as
needed. The owned object is constructed using the function
`allocator_traits<allocator_type>::rebind_traits<U>::construct` and destroyed
using the function
`allocator_traits<allocator_type>::rebind_traits<U>::destroy`, where `U` is
either `allocator_type::value_type` or an internal type used by the polymorphic
value._
There is, perhaps, no need to mention allocators again for individual constructors.
=> Amend wording after discussion with Jonathan Wakely

DRAFT.md
Use "may be X only" rather that "may only be X".
=> Amend draft to add missing explicit on indirect ctor in synopsis

DRAFT.md
Note that I did not update the revision history. I thought that following bullet point might cover my change:
```markdown
* Fix specification of `<=>` to use `synth-three-way-result`.
```
I you think otherwise, I am happy to add a new bullet point.
Fixes https://github.com/jbcoe/value_types/issues/503
=> Remove noexcept specification from operator<=>

DRAFT.md
=> Sort constraints, remove needless constraints

.github/workflows/cmake.yml, CMakeLists.txt
Use up-to-date googletest to avoid windows CI timeouts fetching from archive
=> Fix failing windows CI

cmake/coverage.cmake, cmake/xyz_add_test.cmake
Fix warning for google test discovery following https://stackoverflow.com/questions/73457020/how-to-set-working-folder-when-running-ctest
Previously we saw:
```
CMake Warning (dev) at cmake/coverage.cmake:344:
Syntax Warning in cmake code at column 50
Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
CMakeLists.txt:25 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
...
```
CMake Warning (dev) at /opt/homebrew/share/cmake/Modules/GoogleTest.cmake:559 (cmake_parse_arguments):
The WORKING_DIRECTORY keyword was followed by an empty string or no value
at all.  Policy CMP0174 is not set, so cmake_parse_arguments() will unset
the arg_WORKING_DIRECTORY variable rather than setting it to an empty
string.
Call Stack …
```
=> Fix CMake warnings

.vscode/c_cpp_properties.json, .vscode/extensions.json, scripts/cmake.sh
Generate compile_commands.json in CMake builds. 
Configure VsCode to read compile_commands.json from default CMake build directory.
=> Generate and use compile_commands.json with CMake

.github/workflows/bazel.yml, .github/workflows/cmake.yml, .github/workflows/code_coverage.yml, .github/workflows/integrity_checks.yml
=> Only run CI checks on relevant changes

.vscode/settings.json, BUILD.bazel, CMakeLists.txt, MODULE.bazel.lock, polymorphic_no_vtable.cc, polymorphic_no_vtable.h, polymorphic_test.cc
This is an amendment of https://github.com/jbcoe/value_types/pull/567 that introduces a parallel implementation of polymorphic rather than replacing the existing one.
Co-authored with @toughengineer
---
Following discussion in #559 I replaced inheritance and virtual functions with a single pointer to function.
With the current benchmarks I could not reliably measure the difference in performance so I assumed that it is not significantly different.
I could however very easily measure the difference in resulting binary size.
Here's the size of **polymorphic_test.exe** in KB:
|compiler|current size|size after change|difference|
|-|-|-|-|
|MSVC|921|904|-17|
|Clang|996|982|-14|
I did not investigate what exactly contributed to overhead, I bet it's RTTI, and maybe vtables and individual …
=> Add implementation of polymorphic that uses no vtable
