.github/workflows/cmake.yml
Compilation fails, perhaps C++20 support is not sufficiently implemented?
=> Disable Clang 14, 15 on Ubuntu CI

BUILD.bazel, CMakeLists.txt, WORKSPACE.bazel, indirect_gtest.cc, polymorphic_gtest.cc
Write code without knowing about implementation details.
May be enlightening, seems to be as some tests need to be disabled.
=> Add Google tests for MVP functionality

polymorphic_with_allocators.h
=> Avoid vtable for getting pointer from control block

indirect.h, indirect_test.cc
=> Allow comparison between different indirects and values

indirect.h, indirect_test.cc, polymorphic.h, polymorphic_test.cc
=> Try to raise code coverage

indirect.h, polymorphic.h
=> Call std::swap directly

BUILD.bazel, DRAFT.md, indirect.h, indirect_consteval.cc, polymorphic.h, polymorphic_consteval.cc
Renders #47 obsolete
Fixes #41
=> Constexpr all-the-things

DRAFT.md
Minor typo and grammatical edits to draft paper.
=> Fix minor typos

CMakeLists.txt, DRAFT.md, README.md, indirect.h, indirect_test.cc, polymorphic.h, polymorphic_test.cc
=> Use traits to determine allocator propagation

DRAFT.md, indirect.h, polymorphic.h
@Ukilele I think this does what you suggested.
=> Remove specialisations of uses_allocator

.github/workflows/bazel.yml
This should be a boilerplate change - just makes checks/actions/workflow information more informative
=> Add more descriptive names for bazel CI actions

.clang-format, .github/workflows/integrity_checks.yml, .gitignore, .pre-commit-config.yaml, CMakeLists.txt, CODEOWNERS, DRAFT.md, README.md, docs/developer-guide.md, presentations/value_types_2023_10_27.md, requirements.txt
The included integrity checks workflow will validate github action files
=> Preinstall hooks

DRAFT.md
=> Tidy layout in code for multiple-argument functions

DRAFT.md, indirect.h
=> Discuss operator() operator[] and emplace

DRAFT.md
Wording is mostly adopted from indirect.
=> Update wording for polymorphic swap and assign for allocator-awareness

DRAFT.md
=> Minor update DRAFT.md

DRAFT.md
Remove duplicated reference to reference implementation
=> remove duplicated reference to reference implementation

DRAFT.md, indirect.h, polymorphic.h
@villevoutilainen thanks for your diligence on this.
=> Make noexcept spec for swap consistent with vector

DRAFT.md
=> Add David Stone's thought on variant dissimilarities

.bazelrc, cmake/vt_add_test.cmake
Ignore:
move-assign-to-self
delete-non-abstract-non-virtual-dtor
=> Silence compiler noise

DRAFT.md
Minor edit of text and table created by @jbcoe.
=> Add section design choices, alternatives and breaking changes

DRAFT.md
Thanks Lewis for all your invaluable help!
=> Add Lewis Baker to Acknowledgements

DRAFT.md, feature_check.h, indirect.h, indirect_test.cc
=> Add template argument deduction guides for indirect

indirect.h, polymorphic.h
=> Allocator-extended move constructor should be conditionally noexcept

DRAFT.md, indirect.h, polymorphic.h
Fixes #235
See https://abseil.io/tips/142
=> Make all default and value constructors explicit

polymorphic.h
=> Assert copy-constructible in polymorphic ctors

DRAFT.md
=> Remove unreferences exposition only p

DRAFT.md
=> Specify uses-allocator construction

DRAFT.md
=> Add wording to say that the default constructor can throw

DRAFT.md
=> Prohibit specializations of either type

DRAFT.md
Based on: [container.node.dtor]
Fixes #228
=> Mention allocators in destructor wording

DRAFT.md
Using a more specific element when it makes sense.
=> Use returns instead of effects where applicable

presentations/vocabulary_types_2023_11_8.md
We should probably rename this file (not DRAFT.md though!?) or clone it. Change looks good.
=> Add tuple to discussed vocabulary types

DRAFT.md
Fixes: https://github.com/jbcoe/value_types/issues/311
=> Rename exposition only variables

DRAFT.md
=> Amend T requirements

DRAFT.md, indirect.h
=> Minimally implement comparisons for indirect

DRAFT.md
=> Remove 'X value' terms as they are minimally used

DRAFT.md
=> Wording for format changes

DRAFT.md
=> Fix effects for constructor wording

BUILD.bazel, DRAFT.md, indirect_test.cc, polymorphic_test.cc, test_helpers.h
The removed comment seemed too defeatist. :)
=> Use static_assert in tests

BUILD.bazel, DRAFT.md, indirect.h, indirect_cxx14.h, indirect_test.cc, polymorphic.h, polymorphic_cxx14.h, polymorphic_test.cc, tagged_allocator.h, test_helpers.h
=> Fixes for move constructors to handle non-equal allocators

DRAFT.md, indirect.h, indirect_cxx14.h
=> Update assignment wording

.github/workflows/bazel.yml
See https://github.com/jbcoe/value_types/actions/runs/8287450033/job/22679825511?pr=386
=> Disable TSAN on CI as it is failing at HEAD on main

polymorphic.h, polymorphic_cxx14.h
Simplify implementation of polymorphic to make adding more constructors less verbose.
=> Add helper function to create control blocks

.github/workflows/bazel.yml, .github/workflows/cmake.yml
=> Run CMake and Bazel CI daily at 1:00am

DRAFT.md
=> Add brief mention of MISRA and HICPP to justify valueless after move

README.md
=> Mention including C++14 headers in README

.github/workflows/bazel.yml, tagged_allocator.h
=> Re-enable Bazel CI sanitizers

DRAFT.md
Fix several cases of `allocator_traits<Alloc>` where `Alloc` is not defined.
Remove `rebind_traits::` which is not valid, because it's missing a template argument list. It's unnecessary for calling `construct` and `destroy` anyway.
Remove notes giving normative requirements about T being a complete type, replace with _Mandates_ elements. I'm unsure about the `polymorphic` constructor that's intended to use the small buffer optimization. The note says completeness of T depends on allocator behaviour, but that's not true if it also depends on whether a small buffer optim is used (it depends on whether T fits in the buffer, which requires T to be complete!)
Fix `noexcept(see below)` in `indirect` synopsis which is just an unconditional `noexcept` on the detailed description (and the effects …
=> Various fixes related to allocators

DRAFT.md
LWG did not review `polymorphic` wording yet but I've applied edits in keeping with what they wanted for `indirect`.
=> Modify DRAFT wording after LWG meeting

DRAFT.md
=> Tidy up DRAFT, minor edits

DRAFT.md, DRAFT_COROLLARY.md
VSCode's davidanson.vscode-markdownlint is on avergae helpful. Help it help us.
=> Minor tweaks to appease markdown linter

DRAFT.md
=> Minor edits to DRAFT.md

DRAFT.md, README.md
Reflect design revision for constraints and comparison
=> Updates to non-technical specification sections

DRAFT.md
=> Add clarifying example for tagged construction

DRAFT.md
Edits applied during LWG review in Hagenberg.
=> Update draft for LWG edits on r13

.github/workflows/cmake.yml, scripts/cmake.sh
=> Use Ninja for CMake

indirect.h
Thanks to https://github.com/ned14 for the concept/SFINAE lesson.
=> Avoid SFINAE in <=> using a lambda.

README.md
=> Fix code coverage badge in README.md
